name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install Chromium
          run: sudo apt-get install chromium-browser
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14.18.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run test:wdio
        # - uses: actions/upload-artifact@v1
        #   if: failure()
        #   with:
        #     name: logs
        #     path: logs